version:  "3.8"



services:
  backend:
    container_name: blog
    image: blog
    restart: always
    build: ./
    ports:
      - "4444:4444"  
    networks:
      - blog_network
  

networks:
  blog_network:
    name: blog_network
    driver: bridge

  
